kind: PersistentVolume
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-local
  annotations:
    helm.sh/resource-policy: keep
  labels:
    app: {{ include "nginx.name" . }}
    chart: {{ include "nginx.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  storageClassName: {{ .Release.Name | quote }}
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  local:
    path: /var/lib/rancher/nginx
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: node-role.kubernetes.io/worker
          operator: Exists
          values:
          - worker

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-local
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: {{ .Release.Name | quote }}
  resources:
    requests:
      storage: 1Gi
